const termsAndConditions = `Terms of Service / Warranty information

Warranty on brand new parts ruled as defective up until 365 days starting the date service/repair was purchased. 
Warranty only valid on brand new part(s) replaced during original service and does not cover labor fees.
No warranty on water/liquid damaged devices, jailbroken devices, rooted devices, and devices repaired previously by someone else other than "Gelatotech".
By using "Gelatotech", your warranty from your service provider or device manufacturer (e.g. Apple store) may or may not get void. 

Your device warranty, if any, may be discontinued or void by using our services, "Gelatotech" cannot guarantee it."Gelatotech" will not be held responsible if your device is refused for any type of warranty replacement from your device manufacturer due to using our services. 
The responsibility is entirely up to the customer.By purchasing and using "Gelatotech" services, you automatically agree to our full terms and conditions.No warranty or refunds on water/liquid damage repairs. "Gelatotech" invests a lot of time and effort into the "attempted" repair/diagnostics of a water/liquid damaged device. "Gelatotech" does not guarantee that water/liquid damaged or any broken device is repairable. All sales are final except on an accessory or physical part (not repair) has been purchased (no refunds for repair services). If an accessory or physical part (not repair) was purchased from "Gelatotech", a refund may be granted with exceptions.If a refund is grated for any reason, it must be requested within 7 days (weekends/holidays included) of purchase date. Refund will be issued once item is physically received back at "Gelatotech". No refunds on repair labor services purchased and rendered.

Items that are purchased, and un-used, after 7 days, will not receive a refund. Refund credit is to the discretion of "Gelatotech". Our 1 year limited warranty only covers any of our part due to manufacture defect, if, and only if the part was installed from "Gelatotech".Warranty is a "part only" exchange and not a "money back" refund. Warranty does not cover your full device, only the parts we used for your device repair (not including labor fees).

"Gelatotech" Terms of Service/Repair
Purchaser of service will truthfully and to the best of his/her own knowledge select the most appropriate repair. "Gelatotech" will do a full inspection on the device prior to repair being completed. If other problems are found with the device, "Gelatotech" will contact the device owner immediately before completing repairs.

If you send "Gelatotech" a device that is beyond repair, we will contact you as soon as possible to discuss return procedure without repair rendered. If you do not truthfully select the right repair (to your best knowledge), we reserve the right to refuse service and return your device back to you."Gelatotech" does not guarantee that we reuse or replace any screen protectors, skins or any kind of custom paraphernalia that may be installed on your device. They may be subject to removal and discarding if need be during repair without customer approval."Gelatotech" is not responsible for cases that might be damaged from removal of device before repair is attempted. If the customers water damaged device can not be repaired satisfactorily, customer will receive the device back in its current state. If your device has water damage, no warranty will be given on the repair. "Gelatotech" retains the right to refuse any repair.

"Gelatotech" General Terms and Conditions
• NO REFUNDS ON REPAIR LABOR CHARGE.
• BROKEN OR CRACKED SCREENS ARE ALREADY OUT OF WARRANTY. ANY SERVICES CONDUCTED TO YOUR DEVICE MAY VOID ANY MANUFACTURE WARRANTY PROVIDED BY MANUFACTURER.
• REPAIR DOES NOT BRING BACK MANUFACTURER WARRANTY.
• NO WARRANTY ON WATER DAMAGES, JAILBROKEN, ROOTED, AND ON DEVICES REPAIRED PREVIOUSLY BY SOMEONE ELSE OTHER THAN "Gelatotech".
• REPAIR MAY REQUIRE US TO SOFTWARE/HARDWARE RESET YOUR DEVICE, CUSTOMER IS SOLELY RESPONSIBLE FOR PROPER BACK UP OF THEIR DEVICES AND PERSONAL INFORMATION AND ARE ENCOURAGED TO DO BACK UP PRIOR TO THE ACTUAL REPAIR BEFORE A REPAIR IS PERFORMED. YOU MAY LOOSE JAILBREAK OR ROOT ACCESS ON YOUR DEVICE IN WHICH "Gelatotech" WILL NOT BE HELD RESPONSIBLE AND SUCH DEVICES ARE NOT COVERED UNDER OUR LIMITED 1 YEAR WARRANTY.
• 365 DAYS, WARRANTY DOES NOT COVER ACCIDENTS, PERSONAL NEGLIGENCE OR ACT OF GOD. ANY PHYSICAL DAMAGED MADE TO YOUR DEVICE AFTER OUR REPAIR WILL VOID YOUR 1 YEAR LIMITED WARRANTY WITH "Gelatotech". ABSOLUTELY NO EXCEPTIONS.
• NO WARRANTY ON ANY PARTS INSTALLED NOT PURCHASED FROM Gelatotech.
• CUSTOMER IS RESPONSIBLE FOR LABOR TO REVERSE ANY INSTALL/SERVICE PERFORMED ON THE DEVICE UPON THEIR REQUEST.
• CUSTOMER IS ADVISED TO BACK UP ANY DATA ON THE DEVICE BEING REPAIR. "Gelatotech" IS NOT RESPONSIBLE FOR ANY DATA LOSS.
• NO REFUND ON SPECIAL ORDERS.
• PRICES FOR REPAIR PARTS AND/OR LABOR CHARGES ARE SUBJECT TO CHANGE WITHOUT NOTICE AT ANY TIME.
Copyright
The entire content included in this site, including but not limited to text, graphics or code is copyrighted as a collective work under the United States and other copyright laws, and is the property of "Gelatotech.". The collective work includes works that are licensed to "Gelatotech". Copyright 2017, "Gelatotech" ALL RIGHTS RESERVED. Permission is granted to electronically copy and print hard copy portions of this site for the sole purpose of placing an order with "Gelatotech" or purchasing "Gelatotech" products. You may display and, subject to any expressly stated restrictions or limitations relating to specific material, download or print portions of the material from the different areas of the site solely for your own non-commercial use, or to place an order with "Gelatotech" or to purchase "Gelatotech" products. Any other use, including but not limited to the reproduction, distribution, display or transmission of the content of this site is strictly prohibited, unless authorized by "Gelatotech". You further agree not to change or delete any proprietary notices from materials downloaded from the site.

Trademarks
All trademarks, service marks and trade names of "Gelatotech " used in the site are trademarks or registered trademarks of "Gelatotech"

Warranty Disclaimer
To the fullest extent permissible pursuant to applicable law, "Gelatotech" disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchant-ability and fitness for a particular purpose and non-infringement. "Gelatotech" does not represent or warrant that the functions contained in the site will be uninterrupted or error-free, that the defects will be corrected, or that this site or the server that makes the site available are free of viruses or other harmful components. "Gelatotech" does not make any warranties or representations regarding the use of the materials in this site in terms of their correctness, accuracy, adequacy, usefulness, timeliness, reliability or otherwise. Some states do not permit limitations or exclusions on warranties, so the above limitations may not apply to you, the purchaser.

Limitation of Liability
"Gelatotech" shall not be liable for any special or consequential damages that result from the use of, or the inability to use, the materials on this site or the performance of the products, even if "Gelatotech " has been advised of the possibility of such damages. Applicable law may not allow the limitation of exclusion of liability or incidental or consequential damages, so the above limitation or exclusion may not apply to you.

Typographical Errors
In the event that a "Gelatotech" product is mistakenly listed at an incorrect price, "Gelatotech " reserves the right to refuse or cancel any orders placed for product listed at the incorrect price. "Gelatotech" reserves the right to refuse or cancel any such orders whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is cancelled, "Gelatotech " shall issue a credit to your credit card account in the amount of the incorrect price. Refunds on credit cards can take 3-7 days to be available on your credit card. If any complications occur, the credit card issuer must be contacted and notified of such complications before "Gelatotech" can issue a trouble ticket. No cash refunds will ever be given on any credit card purchases.

Term; Termination
These terms and conditions are applicable to you upon your accessing the site and/or completing the registration or shopping process either at our physical location or this website or authorized affiliate site. These terms and conditions, or any part of them, may be terminated by "Gelatotech" without notice at any time, for any reason. The provisions relating to Copyrights, Trademark, Disclaimer, Limitation of Liability, Indemnification and Miscellaneous, shall survive any termination.

Notice
"Gelatotech" may deliver notice to you by means of e-mail, a general notice on the site, or by other reliable method to the address you have provided to "Gelatotech".

Miscellaneous
Your use of this site shall be governed in all respects by the laws of the state of California, U.S.A., without regard to choice of law provisions, and not by the 1980 U.N. Convention on contracts for the international sale of goods. You agree that jurisdiction over and venue in any legal proceeding directly or indirectly arising out of or relating to this site (including but not limited to the purchase of "Gelatotech" products) shall be in the state or federal courts located in San Francisco, CA. Any cause of action or claim you may have with respect to the site (including but not limited to the purchase of "Gelatotech "products) must be commenced within one (1) year after the claim or cause of action arises. "Gelatotech" failure to insist upon or enforce strict performance of any provision of these terms and conditions shall not be construed as a waiver of any provision or right. Neither the course of conduct between the parties nor trade practice shall act to modify any of these terms and conditions. "Gelatotech" may assign its rights and duties under this Agreement to any party at any time without notice to you.

Use of Site
Harassment in any manner or form on the site, including via e-mail, chat, or by use of obscene or abusive language, is strictly forbidden. Impersonation of others, including a "Gelatotech" or other licensed employee, host, or representative, as well as other members or visitors on the site is prohibited. You may not upload to, distribute, or otherwise publish through the site any content which is libelous, defamatory, obscene, threatening, invasive of privacy or publicity rights, abusive, illegal, or otherwise objectionable which may constitute or encourage a criminal offense, violate the rights of any party or which may otherwise give rise to liability or violate any law. You may not upload commercial content on the site or use the site to solicit others to join or become members of any other commercial online service or other organization.

Participation Disclaimer
"Gelatotech " does not and cannot review all communications and materials posted to or created by users accessing the site, and is not in any manner responsible for the content of these communications and materials. You acknowledge that by providing you with the ability to view and distribute user-generated content on the site, "Gelatotech" is merely acting as a passive conduit for such distribution and is not undertaking any obligation or liability relating to any contents or activities on the site. However, "Gelatotech " reserves the right to block or remove communications or materials that it determines to be (a) abusive, defamatory, or obscene, (b) fraudulent, deceptive, or misleading, (c) in violation of a copyright, trademark or; other intellectual property right of another or (d) offensive or otherwise unacceptable to "Gelatotech" in its sole discretion.

Indemnification
You agree to indemnify, defend, and hold harmless "Gelatotech", its officers, directors, employees, agents, licensors and suppliers (collectively the "Service Providers") from and against all losses, expenses, damages and costs, including reasonable attorneys' fees, resulting from any violation of these terms and conditions or any activity related to your account (including negligent or wrongful conduct) by you or any other person accessing the site using your Internet account.

Third-Party Links
In an attempt to provide increased value to our visitors, "Gelatotech " may link to sites operated by third parties. However, even if the third party is affiliated with "Gelatotech", "Gelatotech " has no control over these linked sites, all of which have separate privacy and data collection practices, independent of Gelatotech". These linked sites are only for your convenience and therefore you access them at your own risk. Nonetheless, "Gelatotech" seeks to protect the integrity of its web site and the links placed upon it and therefore requests any feedback on not only its own site, but for sites it links to as well (including if a specific link does not work).

Abandoned Devices
In the event that a device is left at our repair facility with no response from customer for 45 days the device becomes property of "Gelatotech". Any attempt to collect an abandoned device after said date left to "Gelatotech" will not be acceptable. "Gelatotech" may sell the abandoned device after 45 days to cover all cost made to the abandoned device that was not paid for. "Gelatotech" will not be held liable after the 45th day of abandonment of device. Day one is the drop off date when the device was received from "Gelatotech".

Mailing In A Device
Please only send in the device. No box or accessories. "Gelatotech" is not responsible for accessories or boxes that are sent in. Do not disassemble the device you are sending in. If you send in a device in pieces," Gelatotech " is not responsible for lost, damaged or missing parts due to a disassembled device that is shipped to us. Customer is responsible for adding insurance to the device they are sending in. Insurance claimes are directed to your shipping service carrier and has nothing to do with "Gelatotech".Gelatotech will not file any claim for the customer nor would Gelatotech contact your shipping provider for any reason. Every client must contact their shipping provider to handle with any issues with shipping.

Price match
Gelatotech offers a price match program that will match any competitors price within a 5 mile radius from our location on 4th St San Francisco, CA 94158. Our price match is not always guaranteed and will only be available depending on the current market price on our purchased parts and weather or not the competitors price includes a similar warranty to match our 1 year warranty. Most phone repair shops only offer a 30-90 day warranty which we will not be able to do a price match with because of our 1 year warranty.

Do it yourself (DIY) Parts Warranty
Parts are tested prior to shipping out or selling locally. They leave our facility tested and working. Our parts only carry a 30 day warranty if, and only if, the part has not been installed by the customer. Once part has been installed then our warranty becomes void to the purchaser. All parts must be tested by our customer prior to installation. Any signs of use, scratches, dust, cracks, liquid damage, removal of any seals or stamps, rips in flex cables will be void through our limited 30 day warranty. All said are considered physical damaged by user and "Gelatotech" will not be held responsible.
A professional technician and professional tools are always recommended for any repair.

Water / Liquid Damage Repair
Unfortunately "Gelatotech" does not offer any type of warranty for any liquid damaged device repair. There are many factors and reasons as to why most repair shops do not offer warranty on liquid damage repairs but the main reason is there is simply no way to tell how long a device will continue to work after a liquid damage repair.Some devices work for weeks or months, some work for years but some can only last a day or hours. Liquid and electronics simply do not work together. Most liquid damage repairs would be for "data recovery" only where we repair the device enough to retrieve photos and videos and save onto a flash drive for the customer. In many cases the device would not be usable to the customer if we decide further repair other than "data recovery" is possible.Some cases we are able to repair the device enough for the customer to be able to take the device home, do a back-up themselves and be able to still use the device. These are the cases in which we must really stress that although the device is "working for now", there is absolutely no way to predict how long the device would work for.

Unforeseen Damages
"Gelatotech" will not be held responsible for any device that may have unforeseen damages prior to our repair. A device may be working ok prior to our repair but unforeseen damages may have occurred during repair. One example of an unforeseen damage: Customers phone has a cracked screen due to a hard fall. The fall might of loosened a chip or filter on the main board which can break off completely during our repair causing the device to act inappropriately or not work completely. All devices brought to us are already broken. We are a repair shop only.
Another example of a device is that is brought to us for repair that has been previously repaired through either a third party repair shop or authorized repair:the previously repaired device might have had a damage internally hidden from eyesight and could have only been noticed after phone or device has been taken apart, which in turn ended up damaging the component further that was probably held together by two components pushing together which causes a sudden unforeseen damage to the device rendering it inoperable. We have seen repairs from other shops with tape holding components together and also really bad soldering jobs that were only temporary repairs."Gelatotech" will not be liable for these situations, by purchasing a repair with "Gelatotech" you automatically agree to all the terms and conditions of our services.


"Gelatotech" is in no way affiliated with any brands or companies who make the devices or products brought to us for repair.


Custom Repairs
"Gelatotech" does not offer any warranty or liability for any damage to a "custom repair". All custom repairs are a labor charge only. Custom repairs are all repairs that are not part of any of our services shown on our website.Every now and then we have customers calling in to do a custom repair such as: soldering wires for a device like a remote control car, external battery, car stereo wires, table lamp, power tools etc.Many times we do take in custom repairs and we enjoy learning new repairs other than our typical repair services but we do not include our warranty services with any custom repairs. "Gelatotech" will not be liable for any damages that may occur either during or after our custom repair job. All custom repair jobs are final price with no refunds given for any reason.



Micro-soldering mother board repairs
** Please note: micro-soldering work requires a lot of high heat from tools to complete a job. Not all devices are repairable and in rare cases high heat can cause further damage to a device. By getting your device repaired through "Gelatotech" you agree to all terms and conditions.Should your device become un-repairable or become further damaged during repair, "Gelatotech" will not be held responsible for further damages that may make your device become permanently damaged. "Gelatotech" will not reimburse or replace any device for any reason. The customer is fully responsible for their device and/or responsible for replacing their own device at their own expense.*** Please note: The "no audio" repairs are more common on CDMA versions model A1660 from Verizon or sprint. AT&T and T-Mobile model A1778 are not as common but also have a risk of losing cell service after audio IC repair. Should this happen then we cannot fix the "no cell service" issue. We will give full refund, we will not reimburse or replace your device if this problem happens after we attempt to repair audio. Your device will not be able to connect to cell service anymore and if restored on iTunes you will not be able to get past the activation screen."Gelatotech" cannot guarantee any board work at all. "Gelatotech" cannot guarantee data recovery should your device become permanently damaged during repair.If your device was working but only had a minor issue that needed soldering work and your device becomes permanently damaged during repair "Gelatotech" will not be held responsible and will not reimburse or replace your device. All repairs are entirely at the customers own risk.Board level repairs do not come cheap and are not a "quick" repair. It takes special equipment, software and skill to diagnose and do this type of repair. There are only a handful of people in the Bay Area who know how to do this work!Repairs can take anywhere from 2-7 business days to repair and in rare cases 1-2 months. If you cannot wait that long, please do not contact me. I can not do rush jobs for anyone. Some repairs take longer than others and I do them all in the order I receive them.I charge more for all "previous repair attempt" jobs. Even if it was just a simple screen replacement gone wrong, many times these are the worst types of damages to the phone (long screw damage). Contact me for quote. Diagnostics for micro-soldering takes a lot of time. I charge a $20.00 diagnostics fee if I cannot repair the device, no exceptions. There will not be a diagnostics fee for successful micro-soldering repair jobs, only the repairs I cannot fix will be charged a $20 diagnostics fee.If a device is non-repairable, the customer has the option to donate their damaged device to "Gelatotech". If a device is donated then "Gelatotech" will waive the $20.00 diagnostics fee.All successful micro-soldering repairs come with a 3 month warranty.
Damages done during our repair
"Gelatotech" will not be held liable for any damages that may occur during or after any our repair job. It is at the customer or purchaser's full responsibility to accept that by getting any device repaired with "Gelatotech" they are doing so at their own risk. By getting a device repaired with "Gelatotech", you, the customer, agree automatically to all of the terms and conditions for "Gelatotech" once your device is in our hands. Please be aware that all devices brought to use all have already been damaged and we are only here to try to repair or refurbish all devices.Some of the damages we've come across were an unforeseen damage, meaning we could not have known about the damage until we have taken the device apart and a sudden damage occurred that was already damaged but became completely damaged once it was touched. This is part of our "unforeseen damage" section.

Refunds or exchanges
"Gelatotech" offers a full 1 year limited warranty only on all the parts we provide for repair only. Our warranty does not cover our parts or your device if it becomes inoperable after a manufacture software update. All our parts are tested for quality prior to installation on the latest OS update that is available during time of installation. Any future updates from the phone manufacture may cause aftermarket part from working. "Gelatotech" will not be held responsible nor will we give any refunds due to this matter. "Gelatotech" has no control over what your devices manufacture does on or after our repair. "Gelatotech" has seen device manufactures release software updates that caused aftermarket phone parts to stop working.
All customers have the option to go to or contact their device manufacture for any repairs at anytime. "Gelatotech" has the right to refuse service to any customer for any reason.

Gelatotech.com has the right to make any changes to all repair prices and terms and conditions at anytime without notification. Terms and conditions last updated December 30, 2020
`;

export default function MicroSolderTerms() {
  return(
  <div>
    <textarea value={termsAndConditions} readOnly={true} disabled className="textarea" aria-invalid="false" rows="10" cols="50"></textarea>
    </div>
  )
};
